name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the application
        run: npm run build

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: Your_Heroku_App_Name
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku login -i
          heroku git:remote -a $HEROKU_APP_NAME
          git push heroku main
